### ISSUE TITLE
Is #NER a built-in macros?

### ISSUE THREAD

**Issue by abbbe** [emora-chat/emora_stdm#14]
I try to follow documentation https://github.com/emora-chat/emora_stdm/blob/master/docs/NatexTutorial.md?plain=1#L129 and use #NER macros as following:
```
from emora_stdm import DialogueFlow

chatbot = DialogueFlow('start')
transitions = {
    'state': 'start',
    '"where do you live?"': {
        '[in, #NER(location)]': {
        },
    }
}
chatbot.load_transitions(transitions)

chatbot.run()
```

When I run this program I get:
```
S: where do you live?
U: in Brussels
ERROR: Macro NER not found
ERROR: Macro NER not found
Traceback (most recent call last):
  File "/Users/abb/Documents/dvp/myass3/test_ner.py", line 13, in <module>
    chatbot.run()
  File "/Users/abb/Documents/dvp/myass3/venv/lib/python3.9/site-packages/emora_stdm/state_transition_dialogue_manager/dialogue_flow.py", line 167, in run
    self.user_turn(user_input, debugging=debugging)
  File "/Users/abb/Documents/dvp/myass3/venv/lib/python3.9/site-packages/emora_stdm/state_transition_dialogue_manager/dialogue_flow.py", line 217, in user_turn
    if next_state in visited or (not self.state_settings(next_state).user_multi_hop):
  File "/Users/abb/Documents/dvp/myass3/venv/lib/python3.9/site-packages/emora_stdm/state_transition_dialogue_manager/dialogue_flow.py", line 826, in state_settings
    return self._graph.data(state)['settings']
  File "/Users/abb/Documents/dvp/myass3/venv/lib/python3.9/site-packages/emora_stdm/state_transition_dialogue_manager/database.py", line 34, in data
    return self._node_data[node]
KeyError: 'None'
```

I have noticed that tests for NER are commented out in code: https://github.com/emora-chat/emora_stdm/blob/master/emora_stdm/test_state_transition_dialogue_manager/test_macros.py#L106 .

Is #NER a built-in macros?

**Comment by jdfinch** [comment]
@abbbe Apologies, I took out the NER built-in macro as part of an update to remove SpaCy as a package dependency, but forgot to update the tutorial. I just updated the tutorial to have a #LEM lemmatizer example instead.
